### PR TITLE
Fix inaccurate and potentially dangerous README documentation

### PR DESCRIPTION
**Pull request by dattocgernon**
Using the documentation in this README led to some unexpected results in my development environment. This PR fixes some inaccuracies, hopefully preventing other engineers from accidentally permanently deleting data in development or production.

### CODE REVIEW

**Review by caseyjmorris — APPROVED** [review]
I'm all for not unintentionally deleting data permanently.

**Review by pmcdermottDatto — APPROVED** [review]
Yes. VERY YES.

**Comment by dattocgernon** [comment]
Sorry, maintainers of xxx! I meant to create this PR in the backupify repository, but for some reason GitHub chose the xxx/master branch as the parent by default and I didn't notice before creating the PR. Feel free to delete this.

**Comment by xxx** [comment]
@dattocgernon haha ack, np. I guess they branched from me a number of years ago.

**Pull request closed without merging**
